In [ ]:
#1.	Download CSV Files & Load Data into SQL (Python & SQL)

import pandas as pd
import mysql.connector as db
from datetime import datetime

user  = 'root'
passcode = "password12*"
host = 'localhost'
db_name = "shopeasy"

db_connection1 = db.connect(
                host  = host,
                user = user,
                password = passcode,
                database = db_name
)

db_connection1
curr = db_connection1.cursor()

sql = """
           create table customer_journey ( JourneyID int, 
                                           CustomerID int, 
                                           ProductID int,
                                           VisitDate date, 
                                           Stage varchar(15), 
                                           Action varchar(10),
                                           Duration int);
               
           create table customer_reviews ( ReviewID int, 
                                           CustomerID int, 
                                           ProductID int,
                                           ReviewDate date, 
                                           Rating int, 
                                           ReviewText varchar(255));
                                           
          create table customers ( CustomerID int, 
                                 CustomerName varchar(50), 
                                 Email varchar(30),
                                 Gender varchar(7),
                                 Age int, 
                                 GeographyID int);

          create table engagement_data ( EngagementID int,
                                CustomerID int, 
                                ContentType varchar(15), 
                                Likes int,
                                EngagementDate date,
                                CampaignID int,
                                ProductID int,
                                ViewsClicksCombined varchar(20));
                             
                                
         create table geography ( GeographyID int, 
                                Country varchar(15), 
                                City varchar(15));
                                
        create table products( ProductID int, 
                               ProductName varchar(20), 
                               Category varchar(10),
                               Price float);
"""
        
curr.execute(sql)

# Commit and close
curr.close()
db_connection1.close()

print("Tables Created successfully.")

In [ ]:
import pandas as pd
import mysql.connector as db
from datetime import datetime
import datetime

csv_file_path1 = r'D:\Customer_Analysis\customer_journey.csv'
csv_file_path2 = r'D:\Customer_Analysis\customer_reviews.csv'
csv_file_path3 = r'D:\Customer_Analysis\customers.csv'
csv_file_path4 = r'D:\Customer_Analysis\engagement_data.csv'
csv_file_path5 = r'D:\Customer_Analysis\geography.csv'
csv_file_path6 = r'D:\Customer_Analysis\products.csv'


data1 = pd.read_csv(csv_file_path1,dayfirst=True)
data2 = pd.read_csv(csv_file_path2,dayfirst=True)
data3 = pd.read_csv(csv_file_path3,dayfirst=True)
data4 = pd.read_csv(csv_file_path4,dayfirst=True)
data5 = pd.read_csv(csv_file_path5,dayfirst=True)
data6 = pd.read_csv(csv_file_path6,dayfirst=True)

print(data1.isnull().sum())  # This shows the count of nulls in each column
print(data1[data1.isnull().any(axis=1)])  # This displays rows with any null values

print(data2.isnull().sum())  # This shows the count of nulls in each column
print(data2[data2.isnull().any(axis=1)])  # This displays rows with any null values

print(data3.isnull().sum())  # This shows the count of nulls in each column
print(data3[data3.isnull().any(axis=1)])  # This displays rows with any null values

print(data4.isnull().sum())  # This shows the count of nulls in each column
print(data4[data4.isnull().any(axis=1)])  # This displays rows with any null values

print(data5.isnull().sum())  # This shows the count of nulls in each column
print(data5[data1.isnull().any(axis=1)])  # This displays rows with any null values

print(data6.isnull().sum())  # This shows the count of nulls in each column
print(data6[data1.isnull().any(axis=1)])  # This displays rows with any null values

user  = 'root'
passcode = "password12*"
host = 'localhost'
db_name = "shopeasy"
  

db_connection = db.connect(
                host  = host,
                user = user,
                password = passcode,
                database = db_name
)
 
cursor = db_connection.cursor()      

data1['VisitDate'] = pd.to_datetime(data1['VisitDate'], errors = 'coerce').dt.strftime("%Y-%m-%d")
data1['Duration'] = data1['Duration'].apply(lambda x: 0 if pd.isna(x) else int(x))

data2['ReviewDate'] = pd.to_datetime(data2['ReviewDate'], errors = 'coerce').dt.strftime("%Y-%m-%d")
data4['EngagementDate'] = pd.to_datetime(data4['EngagementDate'], errors = 'coerce').dt.strftime("%Y-%m-%d")

 
# Insert file Data-1
query1 = """INSERT INTO customer_journey (JourneyID, CustomerID, ProductID, VisitDate, Stage, Action, Duration)
           VALUES (%s, %s, %s, %s, %s, %s, %s)"""

for _, row in data1.iterrows():
    cursor.execute(query1, tuple(row))

# Insert file Data-2
query2 = """INSERT INTO customer_reviews (ReviewID, CustomerID, ProductID, ReviewDate, Rating, ReviewText)
           VALUES (%s, %s, %s, %s, %s, %s)"""

for _, row in data2.iterrows():
    cursor.execute(query2, tuple(row))

# Insert file Data-3
query3 = """INSERT INTO customers (CustomerID, CustomerName, Email, Gender, Age,GeographyID)
           VALUES (%s, %s, %s, %s, %s, %s)"""

for _, row in data3.iterrows():
    cursor.execute(query3, tuple(row))


# Insert file Data-4
query4 = """INSERT INTO engagement_data (EngagementID, CustomerID, ContentType, Likes, EngagementDate, CampaignID, ProductID,ViewsClicksCombined)
           VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"""

for _, row in data4.iterrows():
    cursor.execute(query4, tuple(row))

# Insert file Data-5
query5 = """INSERT INTO geography (GeographyID, Country, City)
           VALUES (%s, %s, %s)"""

for _, row in data5.iterrows():
    cursor.execute(query5, tuple(row))

# Insert file Data-6
query6 = """INSERT INTO products (ProductID, ProductName,Category, Price)
           VALUES (%s, %s, %s, %s)"""

for _, row in data6.iterrows():
    cursor.execute(query6, tuple(row))


# Commit and close
db_connection.commit()

cursor.close()
db_connection.close()

print("Data inserted successfully.")