In [11]:
import datetime

In [3]:
#3.	Customer Journey & Engagement Analysis (SQL):

import pandas as pd
import mysql.connector as db
from datetime import datetime

user  = 'root'
passcode = "password12*"
host = 'localhost'
db_name = "shopeasy"

csv_file_path1 = r'D:\Customer_Analysis\customer_journey.csv'
csv_file_path2 = r'D:\Customer_Analysis\customer_reviews.csv'
data1 = pd.read_csv(csv_file_path1,dayfirst=True)
data2 = pd.read_csv(csv_file_path2,dayfirst=True)

db_connection1 = db.connect(
                host  = host,
                user = user,
                password = passcode,
                database = db_name
)

db_connection1
curr = db_connection1.cursor()

sql = """
          SELECT t1.CustomerID, t1.Action, t2.ProductID FROM shopeasy.customer_journey AS t1 
          INNER JOIN shopeasy.customer_reviews AS t2 ON t1.CustomerID = t2.CustomerID
          WHERE t1.Action = 'purchase';
          
    """

sql1 = """
          SELECT * FROM shopeasy.customer_journey WHERE Action = 'Drop-off';
          
    """

sql2 = """
            SELECT Stage, AVG(Duration) AS Avg_Duration FROM customer_journey
            GROUP BY Stage;
"""
curr.execute(sql)
results1 = curr.fetchall()

curr.execute(sql1)
results2 = curr.fetchall()

curr.execute(sql2)
results3 = curr.fetchall()

# common actions leading to successful conversions - Process results
print("\n",results1)

#Identify drop-off points in the customer journey
print("\n",results2)

#Identify drop-off points in the customer journey
print("\n",results3)


filtered_data1 = data1[data1['Action'] == 'Drop-off']
print(filtered_data1)

#curr.column_names
#dat = curr.fetchall()
#print("common actions leading to successful conversions")
#print("\n",dat)

avg_duration = data.groupby('Stage')['Duration'].mean()
print("\nAverage duration per stage ")
print( avg_duration)

curr.close()
db_connection1.close()

 [(17, 'Purchase', 16), (17, 'Purchase', 6), (89, 'Purchase', 17), (79, 'Purchase', 16)]

 [(1, 64, 18, datetime.date(2024, 6, 10), 'Checkout', 'Drop-off', 0), (2, 94, 11, datetime.date(2025, 7, 9), 'Checkout', 'Drop-off', 0), (4, 33, 18, datetime.date(2025, 5, 28), 'Checkout', 'Drop-off', 0), (11, 23, 12, datetime.date(2023, 8, 22), 'Checkout', 'Drop-off', 0), (21, 58, 20, datetime.date(2024, 3, 7), 'Checkout', 'Drop-off', 0), (24, 77, 6, datetime.date(2025, 6, 25), 'Checkout', 'Drop-off', 0), (32, 67, 11, datetime.date(2023, 9, 4), 'Checkout', 'Drop-off', 0), (37, 38, 17, datetime.date(2024, 6, 18), 'Checkout', 'Drop-off', 0), (47, 30, 20, datetime.date(2024, 2, 18), 'checkout', 'Drop-off', 0), (52, 15, 9, datetime.date(2025, 8, 7), 'Checkout', 'Drop-off', 0), (54, 9, 11, datetime.date(2024, 11, 19), 'checkout', 'Drop-off', 0), (55, 1, 7, datetime.date(2024, 3, 17), 'Checkout', 'Drop-off', 0), (71, 40, 20, datetime.date(2023, 7, 13), 'Checkout', 'Drop-off', 0), (93, 43, 8, datetime.date(2023, 8, 22), 'Checkout', 'Drop-off', 0)]

 [('Checkout', Decimal('45.0500')), ('ProductPage', Decimal('182.7692')), ('Homepage', Decimal('160.5370'))]
    JourneyID  CustomerID  ProductID   VisitDate     Stage    Action  Duration
0           1          64         18   6/10/2024  Checkout  Drop-off       NaN
1           2          94         11    7/9/2025  Checkout  Drop-off       NaN
3           4          33         18   5/28/2025  Checkout  Drop-off       NaN
10         11          23         12   8/22/2023  Checkout  Drop-off       NaN
20         21          58         20    3/7/2024  Checkout  Drop-off       NaN
23         24          77          6   6/25/2025  Checkout  Drop-off       NaN
31         32          67         11    9/4/2023  Checkout  Drop-off       NaN
36         37          38         17   6/18/2024  Checkout  Drop-off       NaN
46         47          30         20   2/18/2024  checkout  Drop-off       NaN
51         52          15          9    8/7/2025  Checkout  Drop-off       NaN
53         54           9         11  11/19/2024  checkout  Drop-off       NaN
54         55           1          7   3/17/2024  Checkout  Drop-off       NaN
70         71          40         20   7/13/2023  Checkout  Drop-off       NaN
92         93          43          8   8/22/2023  Checkout  Drop-off       NaN

AttributeError: 'list' object has no attribute 'groupby'

In [6]:
#4.	Customer Reviews Analysis (SQL & Python)

import pandas as pd
import mysql.connector as db
from datetime import datetime

user  = 'root'
passcode = "password12*"
host = 'localhost'
db_name = "shopeasy"

db_connection = db.connect(
                host  = host,
                user = user,
                password = passcode,
                database = db_name
)

db_connection
curr = db_connection.cursor()

sql1 = """ SELECT p.ProductID, p.ProductName 
            FROM shopeasy.products AS p
            INNER JOIN (
            SELECT ProductID, MAX(Rating) AS Highest_Rating
            FROM shopeasy.customer_reviews
            GROUP BY ProductID
            ) AS cr
            ON p.ProductID = cr.ProductID;
"""
sql2 = """ SELECT s.ProductID, s.ProductName 
            FROM shopeasy.products AS s
            INNER JOIN (
            SELECT ProductID, MIN(Rating) AS Lowest_Rating
            FROM shopeasy.customer_reviews
            GROUP BY ProductID
            ) AS sr
            ON s.ProductID = sr.ProductID;
"""
curr.execute(sql1)
results1 = curr.fetchall()

curr.execute(sql2)
results2 = curr.fetchall()

data_frame1 = pd.DataFrame(results1,columns=curr.column_names)
data_frame1

data_frame2 = pd.DataFrame(results2,columns=curr.column_names)
data_frame2

data_frame1.reset_index(drop=True, inplace=True)
print(data_frame1)

data_frame2.reset_index(drop=True, inplace=True)
print(data_frame2)

curr.close()
db_connection.close()

    ProductID      ProductName
0           1    Running Shoes
1           2  Fitness Tracker
2           3         Yoga Mat
3           4        Dumbbells
4           5      Soccer Ball
5           6    Tennis Racket
6           7       Basketball
7           8  Football Helmet
8           9   Baseball Glove
9          10       Golf Clubs
10         11        Ski Boots
11         12       Ice Skates
12         13     Swim Goggles
13         15    Climbing Rope
14         16            Kayak
15         17        Surfboard
16         18       Volleyball
17         19     Hockey Stick
18         20    Boxing Gloves
    ProductID      ProductName
0           1    Running Shoes
1           2  Fitness Tracker
2           3         Yoga Mat
3           4        Dumbbells
4           5      Soccer Ball
5           6    Tennis Racket
6           7       Basketball
7           8  Football Helmet
8           9   Baseball Glove
9          10       Golf Clubs
10         11        Ski Boots
11         12       Ice Skates
12         13     Swim Goggles
13         15    Climbing Rope
14         16            Kayak
15         17        Surfboard
16         18       Volleyball
17         19     Hockey Stick
18         20    Boxing Gloves
    ProductID      ProductName
0           1    Running Shoes
1           2  Fitness Tracker
2           3         Yoga Mat
3           4        Dumbbells
4           5      Soccer Ball
5           6    Tennis Racket
6           7       Basketball
7           8  Football Helmet
8           9   Baseball Glove
9          10       Golf Clubs
10         11        Ski Boots
11         12       Ice Skates
12         13     Swim Goggles
13         15    Climbing Rope
14         16            Kayak
15         17        Surfboard
16         18       Volleyball
17         19     Hockey Stick
18         20    Boxing Gloves

In [4]:
# 4.Customer Reviews Analysis (SQL & Python):
# ●	Perform basic sentiment analysis in Python.

import pandas as pd
from textblob import TextBlob

df = pd.read_csv("D:\Customer_Analysis\customer_reviews.csv")

def analyze_sentiment(text):
    analysis = TextBlob(text)
    return analysis.polarity, analysis.subjectivity
df["Polarity"], df["Subjectivity"] = zip(*df["ReviewText"].apply(analyze_sentiment))
df.to_csv("D:\Customer_Analysis\sentiment_analysis_results.csv", index=False)
print(df.head())

   ReviewID  CustomerID  ProductID  ReviewDate  Rating  \
0         1          77         18  12/23/2023       3
1         2          80         19  12/25/2024       5
2         3          50         13   1/26/2025       4
3         4          78         15   4/21/2025       3
4         5          64          2   7/16/2023       3

                                 ReviewText  Polarity  Subjectivity
0   Average  experience,  nothing  special.  0.103571      0.485714
1            The  quality  is    top-notch.  1.000000      1.000000
2   Five  stars  for  the  quick  delivery.  0.333333      0.500000
3  Good  quality,  but  could  be  cheaper.  0.700000      0.600000
4   Average  experience,  nothing  special.  0.103571      0.485714

<>:7: SyntaxWarning: invalid escape sequence '\C'
<>:13: SyntaxWarning: invalid escape sequence '\C'
<>:7: SyntaxWarning: invalid escape sequence '\C'
<>:13: SyntaxWarning: invalid escape sequence '\C'
C:\Users\I02062\AppData\Local\Temp\ipykernel_84612\3811548796.py:7: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv("D:\Customer_Analysis\customer_reviews.csv")
C:\Users\I02062\AppData\Local\Temp\ipykernel_84612\3811548796.py:13: SyntaxWarning: invalid escape sequence '\C'
  df.to_csv("D:\Customer_Analysis\sentiment_analysis_results.csv", index=False)

In [5]:
import pandas as pd
import mysql.connector
from textblob import TextBlob

DB_HOST = "localhost"
DB_NAME = "shopeasy"
DB_USER = "root"
DB_PASSWORD = "password12*"

conn = mysql.connector.connect(
    host=DB_HOST,
    database=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD
)
cursor = conn.cursor()

alter_query = """
    ALTER TABLE customer_reviews 
    ADD COLUMN IF NOT EXISTS polarity FLOAT, 
    ADD COLUMN IF NOT EXISTS subjectivity FLOAT;
"""
try:
    cursor.execute(alter_query)
except:
    pass  

query = "SELECT ReviewID, ReviewText FROM customer_reviews"
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["ReviewID", "ReviewText"])

def analyze_sentiment(text):
    if pd.isna(text) or not isinstance(text, str) or text.strip() == "":
        return 0.0, 0.0  # Neutral sentiment for missing or invalid text
    analysis = TextBlob(text)
    return float(analysis.polarity), float(analysis.subjectivity)

df["Polarity"], df["Subjectivity"] = zip(*df["ReviewText"].apply(analyze_sentiment))

update_query = """
    UPDATE customer_reviews
    SET polarity = %s, subjectivity = %s
    WHERE ReviewID = %s
"""
cursor.executemany(update_query, df[["Polarity", "Subjectivity", "ReviewID"]].values.tolist())
conn.commit()
cursor.close()
conn.close()
print("Sentiment analysis results saved to MySQL database.")

ProgrammingError: 1054 (42S22): Unknown column 'polarity' in 'field list'

In [ ]:
#5.	Marketing Effectiveness (SQL):